[build-system]
requires = [
    "setuptools >= 46.4.0",
    "wheel ~= 0.32"
]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"
force_sort_within_sections = true
reverse_relative = true
known_first_party = ["nwb_healthstatus"]
